nys_parking_violations:
  outputs:
    dev: 
      type: duckdb
      path: '../data/parking_violations.db'
    prod:
      type: duckdb
      path: './data/prod_nyc_parking_violations.db'
  target: dev